server:
  port: 8084

spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:postgresql://localhost:5435/notification_db
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.studysprint.common.event"

services:
  user-service:
    url: http://localhost:8081
  task-service:
    url: http://localhost:8082
  planner-service:
    url: http://localhost:8083

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces

logging:
  pattern:
    level: "%5p [${notification-service:},%X{traceId:-},%X{spanId:-}]"