server:
  port: 8083

spring:
  application:
    name: planner-service

  datasource:
    url: jdbc:postgresql://localhost:5432/planner_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

services:
  user-service:
    url: http://localhost:8081
  task-service:
    url: http://localhost:8082
  notification-service:
    url: http://localhost:8084